# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - functions/monkey-importer/*
    - functions/Posmn.CoinData/*
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration) --output publish_output
  workingDirectory: '$(System.DefaultWorkingDirectory)/functions/monkey-importer'
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'function'
    PathtoPublish: '$(System.DefaultWorkingDirectory)/functions/monkey-importer/publish_output'
